name: huda_app
description: Formal Arabic Education for Everyone
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  provider: ^6.1.1
  palette_generator: ^0.3.3
  video_thumbnail: ^0.5.3
  path_drawing: ^1.0.0
  flutter_svg: ^2.0.9
  audioplayers: ^5.2.1
  chewie: ^1.7.4
  flutter_localizations:
    sdk: flutter
  tavus_avatar_flutter: 
    path: ../../MissHudaFunctions/Avatar/tavus_avatar_flutter-optimized

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/flags/
    - assets/videos/
    - assets/videos/letters/
    - assets/images/letters/
    - assets/audio/

  fonts:
    - family: Tufuli Arabic
      fonts:
        - asset: assets/fonts/tufuli-regular.otf
        - asset: assets/fonts/tufuli-bold.otf
          weight: 700